---
# tasks file for AWS
#
- debug:
    var: inventory_hostname
- name: Get AWS Instance Configuration
  vars:
    ansible_become: false
  ec2_instance_info:
    filters:
      "tag:Name": "{{ inventory_hostname }}"
      instance-state-name: ["running"]
    region: "{{ cloud_region }}"
  register: ec2_instance_info
  delegate_to: localhost
  retries: 3
- debug:
    var: ec2_instance_info
- set_fact:
    host_address: "{{ ec2_instance_info.instances[0].network_interfaces[0].private_ip_address }}"
